### ISSUE TITLE
Not getting data

### ISSUE THREAD

**Issue by KrunchMuffin** [UedaTakeyuki/mh-z19#14]
Hi,

I have the mh-z19b. I have installed the library but I am not getting data.
![image](https://user-images.githubusercontent.com/1037197/68902448-5413bf80-0706-11ea-8216-ad13551e0b36.png)

I also tried in a python file with

```
import mh_z19
mh_z19.read()
```
I get `none` back with that.

**Comment by KrunchMuffin** [comment]
Not sure what I did, but I got it working.

**Comment by pepsifan92** [comment]
I had the same `null` - results after install and connected sensor.
Until I **switched the 5V power supply of the sensor off and on again**. After a few seconds, I got expected co2 results.

**Comment by KrunchMuffin** [comment]
Ya, I think that's what I did.

**Comment by UedaTakeyuki** [comment]
Hi, KrunchMuffin,

I'm glad to hear you can get data!
Sorry for my late reply.

**Comment by flaviusone** [comment]
Also getting this after around 3 days of usage (reading every 10 seconds). Restarting the power supply is not a solution for a long time monitoring system. Can we do something from software @UedaTakeyuki?

**Comment by UedaTakeyuki** [comment]
Hi, flaviusone

I'm afraid I have no idea. If restarting works solution, add the logic of automatic restarting can be work when null returns continuously.

**Comment by kpmkpm** [comment]
I have the same issue. Gives null values or 9 with --all flags.

5v Off and On does not work. Any ideas? Broken sensor?

**Comment by UedaTakeyuki** [comment]
Hi kpmkpm,

I think this is hardware matter. The most possible cause might be that the cable connection is loose.

**Comment by Alexs784** [comment]
Hey there! I am having this exact same issue on my Raspberry 3 :/ It used to work, but it doesn't anymore... It stopped working when my old power adapter broke. What I did is order a new one wich supplies 3A if I remember correctly, ordered a new sensor as well (I thought the old one was _broken/burnt_) and changed jumpers but I still get `null` (or `9` when using the `--all` option).
Don't know what else to try... Any ideas?

**Comment by kpmkpm** [comment]
> Hey there! I am having this exact same issue on my Raspberry 3 :/ It used to work, but it doesn't anymore... It stopped working when my old power adapter broke. What I did is order a new one wich supplies 3A if I remember correctly, ordered a new sensor as well (I thought the old one was _broken/burnt_) and changed jumpers but I still get `null` (or `9` when using the `--all` option).
> Don't know what else to try... Any ideas?

My problem was loose soldering. After resoldering the contacts it started to work.

**Comment by pepsifan92** [comment]
You say it's not working since the power adapter changed. I observed, especially with on the raspberry pi (Version >=3), that the supply should output 5,5V, not only 5V, to keep the voltage on the pi always above 5V. The Pi consumes a lot of current in peaks and the voltage drops significant on the board of the pi, because of:
- too long cables
- too thin cables
- too low voltage

Your **mh-z19** could be affected by this issue and the voltage drops there, too. 

Solutions are: 
- short, thick cables
- a capacitor directly connected to 5V & GND pins on the Pi (and your mh-z19) to prevent voltage drops
- Enhance the voltage

I would try the first two things first, maybe it's enougth to prevent voltage drops. 

_(And yes, 5V is the standard voltage for USB. It's a fail on the Raspberry to require 5,5V I think. A 2A Power Adaper should be enough, a pi consumes less than 1A most of the time)_
